---
- name: Add or update notes on an existing VM in VMware
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set notes for the VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: '{{ datacenter_name }}'
        validate_certs: no
        name: "{{ vm_name }}"  # Naziv VM na kojoj se dodaju beleške
        state: present  # Moze biti poweredon, poweredoff, ili absent
        annotation: "{{ vm_notes }}"  # Beleske koje se dodaju ili azuriraju
      delegate_to: localhost
